name: github actions test

on: [push, pull_request]

jobs:
  job_1:
    name: std
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: tests
        shell: bash
        run: |
          df -h
          echo ${HOME}
          echo '*****************'
          echo ${GITHUB_WORKSPACE}
          echo '*****************'
          echo ${GITHUB_EVENT_PATH}
          echo '*****************'
          ls -al ${HOME}
          echo '*****************'
          ls -al ${GITHUB_WORKSPACE}
          echo '*****************'
          ls -al ${GITHUB_EVENT_PATH}
          echo '*****************'
          ls -al /
          echo '*****************'
          ls -al /mnt
          echo '*****************'
          ls -al /var/lib/
          echo '*****************'
          echo '*****************'
          echo '*****************'
          echo '*****************'
          echo '*****************'
          echo '*****************'
          echo '*****************'
